languages = {
    "Afrikaans": "afr",
    "Amharic": "amh",
    "Arabic": "ara",
    "Assamese": "asm",
    "Azerbaijani": "aze",
    "Azerbaijani (Cyrillic)": "aze_cyrl",
    "Belarusian": "bel",
    "Bengali": "ben",
    "Tibetan": "bod",
    "Bosnian": "bos",
    "Breton": "bre",
    "Bulgarian": "bul",
    "Catalan": "cat",
    "Cebuano": "ceb",
    "Czech": "ces",
    "Chinese (Simplified)": "chi_sim",
    "Chinese (Simplified, Vertical)": "chi_sim_vert",
    "Chinese (Traditional)": "chi_tra",
    "Chinese (Traditional, Vertical)": "chi_tra_vert",
    "Cherokee": "chr",
    "Corsican": "cos",
    "Welsh": "cym",
    "Danish": "dan",
    "German": "deu",
    "Dhivehi": "div",
    "Dzongkha": "dzo",
    "Greek": "ell",
    "English": "eng",
    "Middle English": "enm",
    "Esperanto": "epo",
    "Math / Equation": "equ",
    "Estonian": "est",
    "Basque": "eus",
    "Faroese": "fao",
    "Persian": "fas",
    "Filipino": "fil",
    "Finnish": "fin",
    "French": "fra",
    "Frankish": "frk",
    "Middle French": "frm",
    "Western Frisian": "fry",
    "Scottish Gaelic": "gla",
    "Irish": "gle",
    "Galician": "glg",
    "Ancient Greek": "grc",
    "Gujarati": "guj",
    "Haitian Creole": "hat",
    "Hebrew": "heb",
    "Hindi": "hin",
    "Croatian": "hrv",
    "Hungarian": "hun",
    "Armenian": "hye",
    "Inuktitut": "iku",
    "Indonesian": "ind",
    "Icelandic": "isl",
    "Italian": "ita",
    "Old Italian": "ita_old",
    "Javanese": "jav",
    "Japanese": "jpn",
    "Japanese (Vertical)": "jpn_vert",
    "Kannada": "kan",
    "Georgian": "kat",
    "Old Georgian": "kat_old",
    "Kazakh": "kaz",
    "Khmer": "khm",
    "Kyrgyz": "kir",
    "Kurmanji (Kurdish)": "kmr",
    "Korean": "kor",
    "Korean (Vertical)": "kor_vert",
    "Lao": "lao",
    "Latin": "lat",
    "Latvian": "lav",
    "Lithuanian": "lit",
    "Luxembourgish": "ltz",
    "Malayalam": "mal",
    "Marathi": "mar",
    "Macedonian": "mkd",
    "Maltese": "mlt",
    "Mongolian": "mon",
    "Maori": "mri",
    "Malay": "msa",
    "Burmese": "mya",
    "Nepali": "nep",
    "Dutch": "nld",
    "Norwegian": "nor",
    "Occitan": "oci",
    "Odia (Oriya)": "ori",
    "Orientation and Script Detection": "osd",
    "Punjabi": "pan",
    "Polish": "pol",
    "Portuguese": "por",
    "Pashto": "pus",
    "Quechua": "que",
    "Romanian": "ron",
    "Russian": "rus",
    "Sanskrit": "san",
    "Sinhala": "sin",
    "Slovak": "slk",
    "Slovenian": "slv",
    "Sindhi": "snd",
    "Script and Number Detection": "snum",
    "Spanish": "spa",
    "Old Spanish": "spa_old",
    "Albanian": "sqi",
    "Serbian": "srp",
    "Serbian (Latin)": "srp_latn",
    "Sundanese": "sun",
    "Swahili": "swa",
    "Swedish": "swe",
    "Syriac": "syr",
    "Tamil": "tam",
    "Tatar": "tat",
    "Telugu": "tel",
    "Tajik": "tgk",
    "Thai": "tha",
    "Tigrinya": "tir",
    "Tongan": "ton",
    "Turkish": "tur",
    "Uyghur": "uig",
    "Ukrainian": "ukr",
    "Urdu": "urd",
    "Uzbek": "uzb",
    "Uzbek (Cyrillic)": "uzb_cyrl",
    "Vietnamese": "vie",
    "Yiddish": "yid",
    "Yoruba": "yor"
}
